version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore(ci): "
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1

  - package-ecosystem: "pip"
    directory: "/"
    commit-message:
      prefix: "chore(poetry): "
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
